### ISSUE TITLE
veth parsing bug

### ISSUE THREAD

**Issue by coreyhines** [networkRob/rLab-eos#4]
When parsing veth pairs, the current logic to split on "-" does not support EOS DUTs that have "-" in the name like "eos-14", as well as topologies with "-" in the name. The issue is located in build/topo-builder.py on line 251:

    for _veth in VETH_PAIRS:
        _v1, _v2 = _veth.split("-")
        
   Found while working on enhancements to PR #2

**Comment by networkRob** [comment]
Fixed in latest release.
